# ============================================================
# Keybindings
# ============================================================

# Application Shortcuts
bindsym --no-warn Mod4+space exec rofi -show drun
bindsym Mod4+m exec ~/.config/sway/scripts/lock.sh
# Overrides Fedora's default layout toggle (Mod4+e) to launch the file manager instead
bindsym --no-warn Mod4+e exec thunar
bindsym --no-warn Mod4+Delete exec wlogout -b 3 -c 50 -r 50

# Theme & Wallpaper
bindsym Mod4+backslash exec ~/.local/bin/rofi-wallpaper
bindsym Mod4+period exec ~/.config/waybar/scripts/theme-toggle.sh

# Window Management
unbindsym Mod4+v
bindsym Mod4+v floating toggle

# Mouse wheel workspace switching (Hold Super + Scroll)
bindsym --whole-window Mod4+button4 workspace next_on_output
bindsym --whole-window Mod4+button5 workspace prev_on_output
