# ============================================================
# Appearance & Gaps
# ============================================================

# Borders and Gaps
default_border pixel 4
default_floating_border pixel 4
hide_edge_borders --i3 smart

gaps inner 12
gaps outer 8
smart_gaps off

# Focus behavior
focus_follows_mouse yes

# Pywal Borders
# class                 border      bground     text        indicator   child_border
client.focused          $color6     $color6     $background $color6     $color6
client.focused_inactive $color2     $background $color7     $color2     $color2
client.unfocused        $color2     $background $color7     $color2     $color2
client.urgent           $color1     $color1     $foreground $color1     $color1

# SwayFX (Uncomment if you install SwayFX)
# corner_radius 12
# shadows enable
# shadow_blur_radius 20
# shadow_color #00000099
# blur enable
