# ============================================================
# Autostart
# ============================================================

# Night light
exec wlsunset -t 3500 -T 4000

# Core Components
exec_always sh -c 'killall waybar; sleep 0.2; waybar'
exec_always sh -c 'pkill swayidle; swayidle -w \
    timeout 300 "$HOME/.config/sway/scripts/lock.sh" \
    timeout 600 "swaymsg output * dpms off" \
    resume "swaymsg output * dpms on" \
    before-sleep "$HOME/.config/sway/scripts/lock.sh"'

# Window Layout
exec_always autotiling
